import asyncio
import csv
import json
import os
import math
from fastapi import FastAPI, WebSocket
from fastapi.responses import HTMLResponse

app = FastAPI()

# 1. Serve the Frontend
@app.get("/")
async def get_dashboard():
    """Serves the index.html file generated by Claude."""
    try:
        with open("dashboard.html", "r", encoding="utf-8") as f:
            return HTMLResponse(f.read())
    except FileNotFoundError:
        return HTMLResponse("<h2>Error: index.html not found!</h2><p>Please save Claude's output as index.html in this folder.</p>")

# 2. The Live Data Stream (WebSocket)
@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    """Streams FL metrics and XAI wave data to the frontend in real-time."""
    await websocket.accept()
    
    time_step = 0
    
    try:
        while True:
            # --- Read FL Simulation Metrics ---
            current_round = 0
            mae = 0.0
            c0_rqi = 0.0
            c1_rqi = 0.0
            
            if os.path.exists("simulation_log.csv"):
                with open("simulation_log.csv", "r") as f:
                    lines = list(csv.reader(f))
                    if len(lines) > 1:
                        latest = lines[-1]
                        current_round = int(latest[0])
                        mae = float(latest[1])
                        c0_rqi = float(latest[2])
                        c1_rqi = float(latest[3])

            # --- Generate XAI Live Waveform ---
            # Simulating a breathing wave (PPG) with Attention Mechanism spikes
            wave_data = []
            attention_data = []
            
            for i in range(50): # Send 50 data points per frame
                t = (time_step + i) * 0.1
                # Math for a breathing wave pattern
                signal = math.sin(t) + 0.3 * math.sin(2 * t) 
                
                # The "Attention" logic: Model focuses heavily when the signal peaks
                attention = 1.0 if signal > 0.8 else 0.1 
                
                wave_data.append(round(signal, 3))
                attention_data.append(attention)
                
            time_step += 5 # Move the wave forward for the next frame

            # --- Package and Send ---
            payload = {
                "round": current_round,
                "mae": mae,
                "c0_rqi": c0_rqi,
                "c1_rqi": c1_rqi,
                "wave": wave_data,
                "attention": attention_data,
                # Edge simulation stats
                "fp32_mb": 5.4,
                "int8_mb": 1.2
            }
            
            await websocket.send_text(json.dumps(payload))
            await asyncio.sleep(0.5) # Refresh rate: 2 frames per second
            
    except Exception as e:
        print(f"Dashboard disconnected: {e}")